//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChatMessageRole.
const (
	Assistant ChatMessageRole = "assistant"
	System    ChatMessageRole = "system"
	Tool      ChatMessageRole = "tool"
	User      ChatMessageRole = "user"
)

// Defines values for DocumentStatus.
const (
	Failed     DocumentStatus = "failed"
	Processing DocumentStatus = "processing"
	Ready      DocumentStatus = "ready"
	Uploaded   DocumentStatus = "uploaded"
)

// Defines values for ToolCallType.
const (
	ToolCallTypeFunction ToolCallType = "function"
)

// Defines values for ToolDefinitionType.
const (
	ToolDefinitionTypeFunction ToolDefinitionType = "function"
)

// ChatCompletionChoice defines model for ChatCompletionChoice.
type ChatCompletionChoice struct {
	FinishReason *string     `json:"finish_reason"`
	Index        int         `json:"index"`
	Message      ChatMessage `json:"message"`
}

// ChatCompletionChunk defines model for ChatCompletionChunk.
type ChatCompletionChunk struct {
	Choices []ChatCompletionChunkChoice `json:"choices"`
	Created int64                       `json:"created"`
	Id      string                      `json:"id"`
	Model   string                      `json:"model"`
	Object  string                      `json:"object"`
}

// ChatCompletionChunkChoice defines model for ChatCompletionChunkChoice.
type ChatCompletionChunkChoice struct {
	Delta        ChatMessageDelta `json:"delta"`
	FinishReason *string          `json:"finish_reason"`
	Index        int              `json:"index"`
}

// ChatCompletionRequest defines model for ChatCompletionRequest.
type ChatCompletionRequest struct {
	MaxTokens   *int                 `json:"max_tokens,omitempty"`
	Messages    []ChatMessage        `json:"messages"`
	Metadata    *ChatRequestMetadata `json:"metadata,omitempty"`
	Model       string               `json:"model"`
	Stream      *bool                `json:"stream,omitempty"`
	Temperature *float32             `json:"temperature,omitempty"`

	// ToolChoice OpenAI-compatible tool choice field.
	ToolChoice *interface{}      `json:"tool_choice"`
	Tools      *[]ToolDefinition `json:"tools,omitempty"`
}

// ChatCompletionResponse defines model for ChatCompletionResponse.
type ChatCompletionResponse struct {
	Choices []ChatCompletionChoice `json:"choices"`
	Created int64                  `json:"created"`
	Debug   *DebugInfo             `json:"debug,omitempty"`
	Id      string                 `json:"id"`
	Model   string                 `json:"model"`
	Object  string                 `json:"object"`
	Usage   *Usage                 `json:"usage,omitempty"`
}

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	// Content Message content. Can be string or structured content.
	Content    *interface{}    `json:"content"`
	Name       *string         `json:"name,omitempty"`
	Role       ChatMessageRole `json:"role"`
	ToolCallId *string         `json:"tool_call_id,omitempty"`
	ToolCalls  *[]ToolCall     `json:"tool_calls,omitempty"`
}

// ChatMessageRole defines model for ChatMessage.Role.
type ChatMessageRole string

// ChatMessageDelta defines model for ChatMessageDelta.
type ChatMessageDelta struct {
	Content   *string     `json:"content,omitempty"`
	Role      *string     `json:"role,omitempty"`
	ToolCalls *[]ToolCall `json:"tool_calls,omitempty"`
}

// ChatRequestMetadata defines model for ChatRequestMetadata.
type ChatRequestMetadata struct {
	ConversationId *string `json:"conversation_id,omitempty"`
	SessionEnd     *bool   `json:"session_end,omitempty"`
	UserId         *string `json:"user_id,omitempty"`
}

// DebugInfo defines model for DebugInfo.
type DebugInfo struct {
	AgentEnabled    *bool          `json:"agent_enabled,omitempty"`
	AgentIterations *int           `json:"agent_iterations,omitempty"`
	ConversationId  *string        `json:"conversation_id,omitempty"`
	FallbackReason  *string        `json:"fallback_reason,omitempty"`
	MemoryHits      *int           `json:"memory_hits,omitempty"`
	Mode            *string        `json:"mode,omitempty"`
	Sources         *[]DebugSource `json:"sources,omitempty"`
	ToolsInvoked    *[]string      `json:"tools_invoked,omitempty"`
}

// DebugSource defines model for DebugSource.
type DebugSource struct {
	Category   *string  `json:"category,omitempty"`
	DocumentId *string  `json:"document_id,omitempty"`
	Filename   *string  `json:"filename,omitempty"`
	Score      *float32 `json:"score,omitempty"`
}

// Document defines model for Document.
type Document struct {
	Category    *string        `json:"category,omitempty"`
	Confidence  *float64       `json:"confidence,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
	Error       *string        `json:"error,omitempty"`
	Filename    string         `json:"filename"`
	Id          string         `json:"id"`
	MimeType    string         `json:"mime_type"`
	Status      DocumentStatus `json:"status"`
	StoragePath string         `json:"storage_path"`
	Subcategory *string        `json:"subcategory,omitempty"`
	Summary     *string        `json:"summary,omitempty"`
	Tags        *[]string      `json:"tags,omitempty"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// DocumentStatus defines model for Document.Status.
type DocumentStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// FunctionCall defines model for FunctionCall.
type FunctionCall struct {
	Arguments string `json:"arguments"`
	Name      string `json:"name"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// ModelListResponse defines model for ModelListResponse.
type ModelListResponse struct {
	Data   []ModelObject `json:"data"`
	Object string        `json:"object"`
}

// ModelObject defines model for ModelObject.
type ModelObject struct {
	Created *int64 `json:"created,omitempty"`
	Id      string `json:"id"`
	Object  string `json:"object"`
	OwnedBy string `json:"owned_by"`
}

// RagAnswerResponse defines model for RagAnswerResponse.
type RagAnswerResponse struct {
	Sources []RetrievedChunk `json:"sources"`
	Text    string           `json:"text"`
}

// RagQueryRequest defines model for RagQueryRequest.
type RagQueryRequest struct {
	Category *string `json:"category,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Question string  `json:"question"`
}

// RetrievedChunk defines model for RetrievedChunk.
type RetrievedChunk struct {
	Category   string  `json:"category"`
	DocumentId string  `json:"document_id"`
	Filename   string  `json:"filename"`
	Score      float64 `json:"score"`
	Text       string  `json:"text"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Function FunctionCall `json:"function"`
	Id       string       `json:"id"`
	Type     ToolCallType `json:"type"`
}

// ToolCallType defines model for ToolCall.Type.
type ToolCallType string

// ToolDefinition defines model for ToolDefinition.
type ToolDefinition struct {
	Function ToolFunctionDefinition `json:"function"`
	Type     ToolDefinitionType     `json:"type"`
}

// ToolDefinitionType defines model for ToolDefinition.Type.
type ToolDefinitionType string

// ToolFunctionDefinition defines model for ToolFunctionDefinition.
type ToolFunctionDefinition struct {
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
	Parameters  *map[string]interface{} `json:"parameters,omitempty"`
}

// Usage defines model for Usage.
type Usage struct {
	CompletionTokens int `json:"completion_tokens"`
	PromptTokens     int `json:"prompt_tokens"`
	TotalTokens      int `json:"total_tokens"`
}

// UploadDocumentMultipartBody defines parameters for UploadDocument.
type UploadDocumentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// ChatCompletionsJSONRequestBody defines body for ChatCompletions for application/json ContentType.
type ChatCompletionsJSONRequestBody = ChatCompletionRequest

// UploadDocumentMultipartRequestBody defines body for UploadDocument for multipart/form-data ContentType.
type UploadDocumentMultipartRequestBody UploadDocumentMultipartBody

// QueryRagJSONRequestBody defines body for QueryRag for application/json ContentType.
type QueryRagJSONRequestBody = RagQueryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// OpenAI-compatible chat completions endpoint
	// (POST /v1/chat/completions)
	ChatCompletions(w http.ResponseWriter, r *http.Request)
	// Upload a document for asynchronous processing
	// (POST /v1/documents)
	UploadDocument(w http.ResponseWriter, r *http.Request)
	// Get document status and metadata
	// (GET /v1/documents/{document_id})
	GetDocumentById(w http.ResponseWriter, r *http.Request, documentId string)
	// List available OpenAI-compatible chat models
	// (GET /v1/models)
	ListModels(w http.ResponseWriter, r *http.Request)
	// RAG query against indexed chunks
	// (POST /v1/rag/query)
	QueryRag(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChatCompletions operation middleware
func (siw *ServerInterfaceWrapper) ChatCompletions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChatCompletions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadDocument operation middleware
func (siw *ServerInterfaceWrapper) UploadDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentById operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "document_id" -------------
	var documentId string

	err = runtime.BindStyledParameterWithOptions("simple", "document_id", r.PathValue("document_id"), &documentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "document_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentById(w, r, documentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListModels operation middleware
func (siw *ServerInterfaceWrapper) ListModels(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListModels(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryRag operation middleware
func (siw *ServerInterfaceWrapper) QueryRag(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryRag(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc("POST "+options.BaseURL+"/v1/chat/completions", wrapper.ChatCompletions)
	m.HandleFunc("POST "+options.BaseURL+"/v1/documents", wrapper.UploadDocument)
	m.HandleFunc("GET "+options.BaseURL+"/v1/documents/{document_id}", wrapper.GetDocumentById)
	m.HandleFunc("GET "+options.BaseURL+"/v1/models", wrapper.ListModels)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rag/query", wrapper.QueryRag)

	return m
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse HealthResponse

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChatCompletionsRequestObject struct {
	Body *ChatCompletionsJSONRequestBody
}

type ChatCompletionsResponseObject interface {
	VisitChatCompletionsResponse(w http.ResponseWriter) error
}

type ChatCompletions200JSONResponse ChatCompletionResponse

func (response ChatCompletions200JSONResponse) VisitChatCompletionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ChatCompletions200TexteventStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response ChatCompletions200TexteventStreamResponse) VisitChatCompletionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "text/event-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ChatCompletions400JSONResponse ErrorResponse

func (response ChatCompletions400JSONResponse) VisitChatCompletionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ChatCompletions401JSONResponse ErrorResponse

func (response ChatCompletions401JSONResponse) VisitChatCompletionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ChatCompletions500JSONResponse ErrorResponse

func (response ChatCompletions500JSONResponse) VisitChatCompletionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ChatCompletions503JSONResponse ErrorResponse

func (response ChatCompletions503JSONResponse) VisitChatCompletionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocumentRequestObject struct {
	Body *multipart.Reader
}

type UploadDocumentResponseObject interface {
	VisitUploadDocumentResponse(w http.ResponseWriter) error
}

type UploadDocument202JSONResponse Document

func (response UploadDocument202JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocument400JSONResponse ErrorResponse

func (response UploadDocument400JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocument500JSONResponse ErrorResponse

func (response UploadDocument500JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocument503JSONResponse ErrorResponse

func (response UploadDocument503JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentByIdRequestObject struct {
	DocumentId string `json:"document_id"`
}

type GetDocumentByIdResponseObject interface {
	VisitGetDocumentByIdResponse(w http.ResponseWriter) error
}

type GetDocumentById200JSONResponse Document

func (response GetDocumentById200JSONResponse) VisitGetDocumentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentById404JSONResponse ErrorResponse

func (response GetDocumentById404JSONResponse) VisitGetDocumentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ListModelsRequestObject struct {
}

type ListModelsResponseObject interface {
	VisitListModelsResponse(w http.ResponseWriter) error
}

type ListModels200JSONResponse ModelListResponse

func (response ListModels200JSONResponse) VisitListModelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListModels401JSONResponse ErrorResponse

func (response ListModels401JSONResponse) VisitListModelsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type QueryRagRequestObject struct {
	Body *QueryRagJSONRequestBody
}

type QueryRagResponseObject interface {
	VisitQueryRagResponse(w http.ResponseWriter) error
}

type QueryRag200JSONResponse RagAnswerResponse

func (response QueryRag200JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type QueryRag400JSONResponse ErrorResponse

func (response QueryRag400JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type QueryRag500JSONResponse ErrorResponse

func (response QueryRag500JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type QueryRag503JSONResponse ErrorResponse

func (response QueryRag503JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// OpenAI-compatible chat completions endpoint
	// (POST /v1/chat/completions)
	ChatCompletions(ctx context.Context, request ChatCompletionsRequestObject) (ChatCompletionsResponseObject, error)
	// Upload a document for asynchronous processing
	// (POST /v1/documents)
	UploadDocument(ctx context.Context, request UploadDocumentRequestObject) (UploadDocumentResponseObject, error)
	// Get document status and metadata
	// (GET /v1/documents/{document_id})
	GetDocumentById(ctx context.Context, request GetDocumentByIdRequestObject) (GetDocumentByIdResponseObject, error)
	// List available OpenAI-compatible chat models
	// (GET /v1/models)
	ListModels(ctx context.Context, request ListModelsRequestObject) (ListModelsResponseObject, error)
	// RAG query against indexed chunks
	// (POST /v1/rag/query)
	QueryRag(ctx context.Context, request QueryRagRequestObject) (QueryRagResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChatCompletions operation middleware
func (sh *strictHandler) ChatCompletions(w http.ResponseWriter, r *http.Request) {
	var request ChatCompletionsRequestObject

	var body ChatCompletionsJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChatCompletions(ctx, request.(ChatCompletionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChatCompletions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChatCompletionsResponseObject); ok {
		if err := validResponse.VisitChatCompletionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadDocument operation middleware
func (sh *strictHandler) UploadDocument(w http.ResponseWriter, r *http.Request) {
	var request UploadDocumentRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadDocument(ctx, request.(UploadDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadDocumentResponseObject); ok {
		if err := validResponse.VisitUploadDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocumentById operation middleware
func (sh *strictHandler) GetDocumentById(w http.ResponseWriter, r *http.Request, documentId string) {
	var request GetDocumentByIdRequestObject

	request.DocumentId = documentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentById(ctx, request.(GetDocumentByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentByIdResponseObject); ok {
		if err := validResponse.VisitGetDocumentByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListModels operation middleware
func (sh *strictHandler) ListModels(w http.ResponseWriter, r *http.Request) {
	var request ListModelsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListModels(ctx, request.(ListModelsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListModels")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListModelsResponseObject); ok {
		if err := validResponse.VisitListModelsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueryRag operation middleware
func (sh *strictHandler) QueryRag(w http.ResponseWriter, r *http.Request) {
	var request QueryRagRequestObject

	var body QueryRagJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueryRag(ctx, request.(QueryRagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueryRag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueryRagResponseObject); ok {
		if err := validResponse.VisitQueryRagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaS3MbuRH+KygkR4qU105qizdZ3jiqsmLHXp82LlZz0ORgjQHGQI9sWsX/ngLmPYPh",
	"YyPJOeyNIoDG1w/0193UPU9MlhuNmhxf3nOXpJhB+HidAl2bLFdI0ujr1MgE/fe5NTlakhh2baSWLl1Z",
	"BGe0/0IXSsFaIV+SLXDGaZcjX3JHVuot38+41AK/+Z3VitSEW7R+KUPnYBtu+avFDV/yvyxafIsK3MIj",
	"u6227vczbvFLIS0Kvvytkt6K+tQgMOvfMSF/zVCzQn8eK5YEhcNHSZi5U0ANhFY22zcQwFrY+b8Ti0Ae",
	"8D3fGJsBlXb4+ws+i5hFio65WkNmRqCKrlSqLu85fgMPiS95kgLNkwbgPAlqj/wzNKfgjbgWdn33rLHS",
	"iWaeiiKBiuAMt78K+/ezhwy/iUAqoR3X7z1+KdDRWLcMvq3IfEbtDgb9eZHWhP84tjIkEHCaOSvQt/WR",
	"g1HlyCJknaW1MQpBBxCY5WiBCou9oN4oA9RGmS6ydak1GaNWSRMOAl1iZe4NyZf8bY766ubCgwaSa4XM",
	"b2fldraRqMSczwa+roSebsdfjVGv0EdQuHZkykFA1CHf+OuUmHC50Q4fPrs8TGIRuC62x65+5Tfd6I15",
	"rFTEI6+0OIUHPsYZ4H9MWbctCQ18ZjShpnG4VidYtWHOrkGzNbJSHWas/1Qk/nGIZlMsfjVkGLWiNSos",
	"oC4yr6PbOcKMezuh5TMOzklHoMNTM0Z1lGuFlE8OlFpNeLHZcN4bugaljr6eoMERk7+qWWDS7pOGeXRd",
	"oriH6TMG/Q6tAx8oU1Z36JxfRi3K0NpAoYgvN6BcS2CdXOt9HhcWw9k+3xE62KKmFWofgyKe18stknxu",
	"l2aKwk5RcwNKrSH53OHqcRrBzNjdKpU0xZVGxN3tTGHPyafBKh/CoVgaDUSykvrOfC4t0wgdB9rRSOne",
	"NY4QINwau4vKFiYpsuCACZtKhZM5wyXmNDKOYq5uPhNwYvRGCtRJ/2JhCp/mImVAlZ5XQP0DQHhBMsMY",
	"N6C1xp5vjynqkhmuym+jNQ9Q4bqpt8iVAREYJbcm8Y9Xb7lPdiB23Me59K8ploAdGQtbXOVAafy2Yn3Q",
	"vK7IMphYI9i6cyJ1xotcnGn7GNM2Nu+acqBrY8eew3sIYtTwi3f0dA01FQcDlOW2mPx/FDoJ5ZRP+uPs",
	"aLfhCcSNORFmg7srw7SiYjD+iaAondazE4NNCWWOt27VsdiNt74UeiMdTV9a89lJ2TTIe9uIHwZarAZU",
	"0tFRFZoqLqCZ1ORtI3+Qqh6iy46Br0vJ8eavGsVqvTseGf0qtTkX0/E9bK+0+4oHnsK59PceyUq8Q1EO",
	"P2IMiN/ouBZhV8u+E+j/XaDdTfbHBzOekpkMZzKpZeYz8LOY74JoGa0qBoibnVGsfbP8ULKe5szTXNOF",
	"08vSjRKzxn3h8phBmpJ4PPercuexSOvl2OlXVhNwzbKN+E8nkVBFOpFTfV067f4f1sjLqbWKjQ/+iBKn",
	"4o/cG5mldXrT05lrxnOwkCGhLelPiHABqHcd8b2hWo0tRnoxDT5O9dX1JODgnCy3Jsvp4BYyBOrAjgHQ",
	"vsRZBMhA5FipfZgols1VfyjwIcfkYiOtI3b17ia0/RYSYhtjmdTbMgvNWP1MWUnXMwZasPdXr9kXnzTn",
	"/wnTEUmBdt6hdd4h7OqGXdUdv5fOZ9z3X+XFl/Nn88tARjlqyCVf8ufzy/lzX7ACpcEwizTUHN/95y2G",
	"bGLyqse7EXxZ1STfQ11bkk4499Pl5aAjhzxXMgkHF79XfV35Uo69o0HZE0zZN6G3m3SsxFo2V00FzN/I",
	"O9ToHMutWZdToMXds0WSAi1aRwbUuXERFfsjNcfL2EBHL43YPZiW8SHxvh+K1fjn0Uw9MZXcV2SywDvU",
	"dNHOd1upg5hGe4f2wvl4DWccKw+xr5JSNh7bhh8Z3DxS6I2c7TGy1nHMoisUMWPZhw+/VNf4qH7xgHbp",
	"NxgRUC9BMFv7zN/97Onu/qihoNRY+R2Fv/xvT6n4jSa0PtW44HJWNlEBxfOnQ/ErZrmxYHdMYI5aoE52",
	"zDfYhcVBOojFXi+gHEMtciM1Nbmizr0HksTH0O0305BDOSIrFMkcLC18DXdRN1CtKYY/nKp+wbeWGsqq",
	"7GCpEM7FiehYQvnpwTzXGCTitHqNQZJgTigC5XVmJT/4Ef/5jg69ozLgGbSFifceuJ1OUmu0KVzPlcOX",
	"tLjv9B37yfLiNVIdJi93N2GW1ik+f7vn0sOuZkdlwTpoaPqxPutYavh8Pj0isZ70DrLOr6svLl88ndv/",
	"Zbz3Ci0GPn6NNKw7Q9nZAq3cGuYcbtKLb6Sj23LLI9p4PKyKqOrXmdkwuAMZflNjFfYfy9qDitVRB+AE",
	"Y9W4KxdY2C5CKzDNUeV4BbaPVMEOBzhPXLuOp18Rq/uGCcKuEMj1POpPpvk/ZpqmyWWwBakdsfAvNyiq",
	"rqEUX2pTkkJhFV/ylChfLhbKJKBS42j58+XPl3z/af/fAAAA//97BEp7zCYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
