//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DocumentStatus.
const (
	Failed     DocumentStatus = "failed"
	Processing DocumentStatus = "processing"
	Ready      DocumentStatus = "ready"
	Uploaded   DocumentStatus = "uploaded"
)

// Document defines model for Document.
type Document struct {
	Category    *string        `json:"category,omitempty"`
	Confidence  *float64       `json:"confidence,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
	Error       *string        `json:"error,omitempty"`
	Filename    string         `json:"filename"`
	Id          string         `json:"id"`
	MimeType    string         `json:"mime_type"`
	Status      DocumentStatus `json:"status"`
	StoragePath string         `json:"storage_path"`
	Subcategory *string        `json:"subcategory,omitempty"`
	Summary     *string        `json:"summary,omitempty"`
	Tags        *[]string      `json:"tags,omitempty"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

// DocumentStatus defines model for Document.Status.
type DocumentStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// RagAnswerResponse defines model for RagAnswerResponse.
type RagAnswerResponse struct {
	Sources []RetrievedChunk `json:"sources"`
	Text    string           `json:"text"`
}

// RagQueryRequest defines model for RagQueryRequest.
type RagQueryRequest struct {
	Category *string `json:"category,omitempty"`
	Limit    *int    `json:"limit,omitempty"`
	Question string  `json:"question"`
}

// RetrievedChunk defines model for RetrievedChunk.
type RetrievedChunk struct {
	Category   string  `json:"category"`
	DocumentId string  `json:"document_id"`
	Filename   string  `json:"filename"`
	Score      float64 `json:"score"`
	Text       string  `json:"text"`
}

// UploadDocumentMultipartBody defines parameters for UploadDocument.
type UploadDocumentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// UploadDocumentMultipartRequestBody defines body for UploadDocument for multipart/form-data ContentType.
type UploadDocumentMultipartRequestBody UploadDocumentMultipartBody

// QueryRagJSONRequestBody defines body for QueryRag for application/json ContentType.
type QueryRagJSONRequestBody = RagQueryRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)
	// Upload a document for asynchronous processing
	// (POST /v1/documents)
	UploadDocument(w http.ResponseWriter, r *http.Request)
	// Get document status and metadata
	// (GET /v1/documents/{document_id})
	GetDocumentById(w http.ResponseWriter, r *http.Request, documentId string)
	// RAG query against indexed chunks
	// (POST /v1/rag/query)
	QueryRag(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadDocument operation middleware
func (siw *ServerInterfaceWrapper) UploadDocument(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadDocument(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDocumentById operation middleware
func (siw *ServerInterfaceWrapper) GetDocumentById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "document_id" -------------
	var documentId string

	err = runtime.BindStyledParameterWithOptions("simple", "document_id", r.PathValue("document_id"), &documentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "document_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDocumentById(w, r, documentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// QueryRag operation middleware
func (siw *ServerInterfaceWrapper) QueryRag(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.QueryRag(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.Healthz)
	m.HandleFunc("POST "+options.BaseURL+"/v1/documents", wrapper.UploadDocument)
	m.HandleFunc("GET "+options.BaseURL+"/v1/documents/{document_id}", wrapper.GetDocumentById)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rag/query", wrapper.QueryRag)

	return m
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse HealthResponse

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocumentRequestObject struct {
	Body *multipart.Reader
}

type UploadDocumentResponseObject interface {
	VisitUploadDocumentResponse(w http.ResponseWriter) error
}

type UploadDocument202JSONResponse Document

func (response UploadDocument202JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocument400JSONResponse ErrorResponse

func (response UploadDocument400JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadDocument500JSONResponse ErrorResponse

func (response UploadDocument500JSONResponse) VisitUploadDocumentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentByIdRequestObject struct {
	DocumentId string `json:"document_id"`
}

type GetDocumentByIdResponseObject interface {
	VisitGetDocumentByIdResponse(w http.ResponseWriter) error
}

type GetDocumentById200JSONResponse Document

func (response GetDocumentById200JSONResponse) VisitGetDocumentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDocumentById404JSONResponse ErrorResponse

func (response GetDocumentById404JSONResponse) VisitGetDocumentByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type QueryRagRequestObject struct {
	Body *QueryRagJSONRequestBody
}

type QueryRagResponseObject interface {
	VisitQueryRagResponse(w http.ResponseWriter) error
}

type QueryRag200JSONResponse RagAnswerResponse

func (response QueryRag200JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type QueryRag400JSONResponse ErrorResponse

func (response QueryRag400JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type QueryRag500JSONResponse ErrorResponse

func (response QueryRag500JSONResponse) VisitQueryRagResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Liveness probe
	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)
	// Upload a document for asynchronous processing
	// (POST /v1/documents)
	UploadDocument(ctx context.Context, request UploadDocumentRequestObject) (UploadDocumentResponseObject, error)
	// Get document status and metadata
	// (GET /v1/documents/{document_id})
	GetDocumentById(ctx context.Context, request GetDocumentByIdRequestObject) (GetDocumentByIdResponseObject, error)
	// RAG query against indexed chunks
	// (POST /v1/rag/query)
	QueryRag(ctx context.Context, request QueryRagRequestObject) (QueryRagResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UploadDocument operation middleware
func (sh *strictHandler) UploadDocument(w http.ResponseWriter, r *http.Request) {
	var request UploadDocumentRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UploadDocument(ctx, request.(UploadDocumentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadDocument")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UploadDocumentResponseObject); ok {
		if err := validResponse.VisitUploadDocumentResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDocumentById operation middleware
func (sh *strictHandler) GetDocumentById(w http.ResponseWriter, r *http.Request, documentId string) {
	var request GetDocumentByIdRequestObject

	request.DocumentId = documentId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDocumentById(ctx, request.(GetDocumentByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDocumentById")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDocumentByIdResponseObject); ok {
		if err := validResponse.VisitGetDocumentByIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// QueryRag operation middleware
func (sh *strictHandler) QueryRag(w http.ResponseWriter, r *http.Request) {
	var request QueryRagRequestObject

	var body QueryRagJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.QueryRag(ctx, request.(QueryRagRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "QueryRag")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(QueryRagResponseObject); ok {
		if err := validResponse.VisitQueryRagResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTW8bNxD9KwTb48YrJykQ7E1uC1dAUaQqekoNY0SOVkyWHyZnVSuG/ntBUlpp1yvZ",
	"LtyceluJHM7Me28e+cCF1c4aNBR49cCDWKGG9PmTFa1GQ/HbeevQk8K0IoCwtn4Tv2njkFc8kFem5tuC",
	"C2uWSqIRGJeX1msgXnFp20WDvNgHmFYv0KcAj0Aob4H6AUD4hpQ+ijkkQe+tH02/VA0a0Di6qOTo31pp",
	"vM3/jqwGAmpT32hazatPvHWNBYmSFxEYgSHErQX3CHLDC74E1aDkN8XYYdZDjbcOaDWerV2chTe0WsOJ",
	"NYI61akIdRjfkf8A72ETf7dOvhD7bWzzrlUeZYRCRRA6zI+hHPTa4dgjvFfBAS+7+IyCYoE/R6LnGJw1",
	"AR8r8ZQOBlXmbWPn/4LQ0Op0giPy70G7JkV/eRKWXdhYxjnUUxP+xjNdBdt6gX0qv/e45BX/rjzMa7kb",
	"1nKO5BWuUf64as2XMZ4J7+lpmNKuokt/ovrfW/SbOd61GF7qDY3SKsVoZZSOw3TZ5VCGsM6OkI5W1jxd",
	"cbdztNY+LC8rVe7c7/aEZ5z1mSCsf679PY+a43J6A9c1UXT0peSPAYlHKrO0MZnEILxyGWT+h0PxZql8",
	"IDb9OGPCGvIgiC2tZ8rUGeKC7WtgWd0FAyPZfHrN7qIiLv4ysQZFaUY+og/WQMOmMzYNQQUCk07nBV+j",
	"Dznx5OLyYhJBsA4NOMUr/u5icvEuGivQKrFUrtKIfo3fNSaoIokQa5pJXu1G+Gvy3zxRKe7tZJJItoZ2",
	"lxg41yiRAsvPIcsrj9BTAzZwiQRlH8KImwos17pJ9HVOzX9VazQYAnPeLjAtluvLco9nKtfZMNLbn+mm",
	"6W7irAkMdGXlZtCdbhtSDjyVUXRvJBD0G+yLP0qop9CFMpBldFaIKW5cXIdt5FvcPuLj7avx0QEywsR+",
	"jYEQ6AhlkvHRPb0t+PtX1Eb/hhop6Aok29EWc//wLXPPDKGPYxjQr9GzfBH21Zk1xuAw3xEwCBsjVt4a",
	"24YeekPxlg9H3rQ9OaXXSHtmrjaz9HQCDxoJfeDVpweuYr27p0I21oHp9eVVHEE0VOzNf2gFz5KeRoI0",
	"gElr778d37/ZyF5r5IDja6ShfSf3PhS6o9VDXSY7P+1J+f6H+qwb/fsehy+MZ1nL5DXTD55nIzDHSw/S",
	"roTi/sH0v7P0Vde9DRjUoEwgpozEe5RMxBdZyOfmA7IJtL7hFV8RuaosGyugWdlA1YfJhwnf3mz/CQAA",
	"///3XSqdrg4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
